spring:
  redis:
    host: localhost
    port: 6001
    password: zooredis

## 추후 redis cluster 설정 지원
#  redis:
#    cluster:
#      nodes:
#        - 15.164.98.87:6300
#        - 15.164.98.87:6301
#        - 15.164.98.87:6302
#        - 15.164.98.87:6400
#        - 15.164.98.87:6401
#        - 15.164.98.87:6402
#      max-redirects: 3
#    password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

kafka:
  host: localhost:9092
  groupid: testWebSocketGroupId
  topic:
    test.websocket: zoo.queueing.push.barogo.test.websocket

